### ISSUE TITLE
VPC Isolation and Gateway

### ISSUE THREAD

**Issue by kinoute** [scaleway/kapsule-terraform-multi-az-tutorial#1]
Hello @bene2k1,

Thanks for your great tutorial and code snippets! We are slowly moving our clusters to VPC and if possible to a multi A-Z environment – at least on one cluster, for testing. I have multiple questions regarding your code/tutorial:

- I don't see what isolation (full or controlled) the VPC/Private Network is set to by default? Is there something to do to enable the full isolation?
- Following the previous question, if the full isolation is enabled, we need a Public Gateway also set? I don't see a public gateway in the snippets

Thank you very much!

**Comment by bene2k1** [comment]
Hello @kinoute, 

By default, all Private Networks have "controlled isolation" [enabled](https://www.scaleway.com/en/docs/containers/kubernetes/reference-content/secure-cluster-with-private-network/#what-is-the-difference-between-controlled-isolation-and-full-isolation). To activate full isolation, the [public_ip_disabled attribute](https://registry.terraform.io/providers/scaleway/scaleway/latest/docs/resources/k8s_pool#public_ip_disabled) must be configured as `true` when creating the Private Network using the `k8s_pool` resource.

Please note that for full isolation to be effective, a public gateway within the same VPC as the cluster is required. Failure to meet this condition will result in the option being rejected, and the creation of the pool will fail.

Benedikt

**Comment by kinoute** [comment]
@bene2k1 Thanks for your quick answer! Indeed, I see the `public_ip_disabled` setting now.

Regarding the Public gateway for full isolation private network, I was wondering if it is possible to assign multiple Gateways? 
My concern is about the bandwhich for a whole cluster. The best machine for a Public Gateway is 1Gbps – the other being 100Mbps. 1Gbps might be fine for most of the cases but I was wondering if there is a way to assign multiple Gateways to 

```hcl
resource "scaleway_vpc_private_network" "full_private_network" {
  name   = "full-private-network"
  region = var.region
  tags   = ["${var.env}", "${var.project}"]
}

resource "scaleway_vpc_public_gateway_ip" "gateway_ip" {}

resource "scaleway_vpc_public_gateway" "public_gateway" {
  name        = "public-gateway"
  type        = "VPC-GW-M"
  ip_id       = scaleway_vpc_public_gateway_ip.gateway_ip.id
  enable_smtp = true
  tags        = ["${var.env}", "${var.project}"]
}

resource "scaleway_vpc_gateway_network" "gateway_network" {
  gateway_id         = scaleway_vpc_public_gateway.public_gateway.id
  private_network_id = scaleway_vpc_private_network.full_private_network.id
  enable_masquerade  = true
  ipam_config {
    push_default_route = true
  }
}
```

Thanks again!

**Comment by bene2k1** [comment]
Hello @kinoute,

I just checked it with the network team, and it is not possible to add more than one Public Gateway to a Private Network, but we are working on a larger version that will become available in the future.

Benedikt

**Comment by kinoute** [comment]
@bene2k1 Thanks a lot for your answers and your help. I'm closing the issue now that I don't have any issue regarding your code!
